config/routes.rb
Rails.application.routes.draw do
  resources :coffees
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'homepage', to: 'home#homepage', as: 'homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coffee.rb
class Coffee < ApplicationRecord
    validates :name, presence: true, uniqueness: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: [:show, :edit, :update, :destroy]

  # GET /coffees
  # GET /coffees.json
  def index
    @coffees = Coffee.all
  end

  # GET /coffees/1
  # GET /coffees/1.json
  def show
  end

  # GET /coffees/new
  def new
    @coffee = Coffee.new
  end

  # GET /coffees/1/edit
  def edit
  end

  # POST /coffees
  # POST /coffees.json
  def create
    @coffee = Coffee.new(coffee_params)

    respond_to do |format|
      if @coffee.save
        format.html { redirect_to @coffee, notice: 'Coffee was successfully created.' }
        format.json { render :show, status: :created, location: @coffee }
      else
        format.html { render :new }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffees/1
  # PATCH/PUT /coffees/1.json
  def update
    respond_to do |format|
      if @coffee.update(coffee_params)
        format.html { redirect_to @coffee, notice: 'Coffee was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffee }
      else
        format.html { render :edit }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffees/1
  # DELETE /coffees/1.json
  def destroy
    @coffee.destroy
    respond_to do |format|
      format.html { redirect_to coffees_url, notice: 'Coffee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee
      @coffee = Coffee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_params
      params.require(:coffee).permit(:name, :price, :origin, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to homepage_url
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coffees/_form.html.erb
<%= form_with(model: coffee, local: true) do |form| %>
  <% if coffee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffee.errors.count, "error") %> prohibited this coffee from being saved:</h2>

      <ul>
        <% coffee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= form.label :name %>
    </p>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <p>
      <%= form.label :price %>
    </p>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <p>
      <%= form.label :origin %>
    </p>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <p>
      <%= form.label :description %>
    </p>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coffees/edit.html.erb
<h1>Editing Coffee</h1>

<%= render 'form', coffee: @coffee %>

<%= link_to 'Show', @coffee %> |
<%= link_to 'Back', coffees_path %>

app/views/coffees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffees</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Origin</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffees.each do |coffee| %>
      <tr>
        <td><%= coffee.name %></td>
        <td><%= coffee.price %></td>
        <td><%= coffee.origin %></td>
        <td><%= coffee.description %></td>
        <% if current_user.role == 'Admin' %>
          <td><%= link_to 'Show', coffee %></td>
          <td><%= link_to 'Edit', edit_coffee_path(coffee) %></td>
          <td><%= link_to 'Destroy', coffee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Coffee', new_coffee_path %>

app/views/coffees/new.html.erb
<h1>New Coffee</h1>

<%= render 'form', coffee: @coffee %>

<%= link_to 'Back', coffees_path %>

app/views/coffees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coffee.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @coffee.price %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @coffee.origin %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coffee.description %>
</p>

<%= link_to 'Edit', edit_coffee_path(@coffee) %> |
<%= link_to 'Back', coffees_path %>

app/views/home/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffee Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'home' %>
  </head>
  <body>
    <div class="container">
      <p>
        Welcome <%= current_user.email %>!
        <%= link_to "Log Out", logout_path %>
      </p>
      <p class="title text-center">Welcome to The Coffee World!</p>  
    </div>
  </body>
</html>

app/views/home/index.html.erb
<%= stylesheet_link_tag 'home' %>
<div class="container center_div">
    <div class="text-center form">
        <%= link_to "Sign Up", signup_path %> or 
        <%= link_to "Log In", login_path %>
        <p id="notice"><%= notice %></p>
    </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :template => "coffees/index", locals: { coffees: @coffees } %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RawCoffeeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p>
      <%= form.label :email %>
    </p>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <p>
      <%= form.label :password %>
    </p>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <p>
      <%= form.label :password_confirmation %>
    </p>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <p>
      <%= form.label :role %>
    </p>
    <p>
      <%= form.select :role, ['Admin', 'User'] %>
    </p>
  </div> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <% if current_user.role == 'Admin' %>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'home' %>
<div class="text-center">
    <h1 class="title">New User</h1>
    <%= render 'form', user: @user %>
    <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>